version: "3.4"
services:
    webapp:
        image: configs:latest
        ports:
            - 5000:5000
        networks:
            - webnet
       
        
networks:
    webnet:
       driver: overlay
