version: "3.2"
services:
    messagedb:
        image: mongo:3.4
        networks:
            - mongomessage
    webapp:
        image: mongomessage
        ports:
            - 4000:5000
        networks:
            - mongomessage
        depends_on:
            - messagedb
networks:
    mongomessage: