version: "3.4"
services:
    webapp:
        image: secrets:latest
        ports:
            - 5000:5000
        networks:
            - webnet
        secrets:
            - databaseconfig.cfg
secrets:
   databaseconfig.cfg:
       external:
           name: dbconfig.cfg
networks:
    webnet:
       driver: overlay
