version: "3.4"
services:
    messagedb:
        image: mongo:3.4
        networks:
            - mongomessage
    webapp:
        image: mongomessage-env
        ports:
            - 4000:5000
        networks:
            - mongomessage
        depends_on:
            - messagedb
        environment:
            - MessageConnectionString=mongodb://messagedb
networks:
    mongomessage: