version: "3.2"
services:
    
        image: mongo:3.4
        networks:
            - 
        
        image: 
        ports:
            - 
        networks:
            - 
        depends_on:
            - 
        environment:
            - MessageConnectionString=mongodb://messagedb
networks:
    